### ISSUE TITLE
How to run gui

### ISSUE THREAD

**Issue by xoxoxo13102020** [dpunk1337/ImageProcessingFilterDemonstrationApplication#1]
```
Traceback (most recent call last):
  File "gui.py", line 781, in <module>
    screenMenu()
  File "gui.py", line 99, in screenMenu
    interface[screenMenuStartRow:screenMenuEndRow,screenMenuStartCol:screenMenuEndCol]=img
ValueError: could not broadcast input array from shape (635,410,3) into shape (794,410,3)
```
Could you please help me?

**Comment by dpunk1337** [comment]
I have made the necessary changes in MenuCreatorAndPointArray.py, it should work fine now. The thing is the menuCreator function had default argument values set according to my pc res. Now it should work for different pc's as well.

**Comment by xoxoxo13102020** [comment]
thank you so much <3

**Comment by xoxoxo13102020** [comment]
I checked and got the same error :(

**Comment by dpunk1337** [comment]
I have corrected and rechecked for multiple screen resolutions. It should work now. I am closing the issue now.
